" 需要安装vim-plug
" 需要vim-8.1
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'w0rp/ale'
Plug 'scrooloose/nerdtree'
Plug 'google/vim-maktaba'
Plug 'google/vim-codefmt'
Plug 'google/vim-glaive'
Plug 'Raimondi/delimitMate'
Plug 'fatih/vim-go'
Plug 'haya14busa/incsearch.vim'
Plug 'tomasiser/vim-code-dark'
Plug 'logico-ar/typewriter'
Plug 'alvan/vim-indexer'
" Colors
" See https://github.com/rafi/awesome-vim-colorschemes
Plug 'ayu-theme/ayu-vim'
Plug 'nightsense/carbonized'
Plug 'wadackel/vim-dogrun'
Plug 'jaredgorski/fogbell.vim'
Plug 'whatyouhide/vim-gotham'
Plug 'fcpg/vim-orbital'
Plug 'rakr/vim-two-firewatch'
Plug 'Yggdroot/indentLine'
" Font
Plug 'ryanoasis/vim-devicons'




call plug#end()
filetype plugin indent on
" 调用glive for vim-codefmt
call glaive#Install()
" 设置代码格式化分配器
augroup autoformat_settings
  autocmd FileType bzl AutoFormatBuffer buildifier
  " 工作原因取消掉proto的格式化
  autocmd FileType c,cpp,cc,javascript,proto AutoFormatBuffer clang-format
  autocmd FileType dart AutoFormatBuffer dartfmt
  autocmd FileType go AutoFormatBuffer gofmt
  autocmd FileType gn AutoFormatBuffer gn
  autocmd FileType html,css,json AutoFormatBuffer js-beautify
  autocmd FileType java AutoFormatBuffer google-java-format
  "autocmd FileType python AutoFormatBuffer yapf
  " Alternative: autocmd FileType python AutoFormatBuffer autopep8
augroup END
" 开场启动newcomplete
let g:neocomplete#enable_at_startup = 1
let g:go_def_mode = 'godef'
set t_Co=256
set encoding=UTF-8
set background=light
set termguicolors
let ayucolor="light"
color gruvbox
set shiftwidth=4
set tabstop=4
set nu
set cursorcolumn
set cursorline
set expandtab

" 按键映射
map <C-n> :NERDTreeToggle<CR>
map <C-g> :GoBuild<CR>
" incsearch
set hlsearch
" inc-search
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
" indent-line

set list lcs=tab:\|\    
