" 需要安装vim-plug
" 需要vim-8.1
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'w0rp/ale'
Plug 'scrooloose/nerdtree'
Plug 'google/vim-maktaba'
Plug 'google/vim-codefmt'
Plug 'google/vim-glaive'
Plug 'Raimondi/delimitMate'
Plug 'fatih/vim-go'
Plug 'haya14busa/incsearch.vim'
call plug#end()
filetype plugin indent on
" 调用glive for vim-codefmt
call glaive#Install()
" 设置代码格式化分配器
augroup autoformat_settings
  autocmd FileType bzl AutoFormatBuffer buildifier
  " 工作原因取消掉proto的格式化
  autocmd FileType c,cpp,javascript AutoFormatBuffer clang-format
  autocmd FileType dart AutoFormatBuffer dartfmt
  autocmd FileType go AutoFormatBuffer gofmt
  autocmd FileType gn AutoFormatBuffer gn
  autocmd FileType html,css,json AutoFormatBuffer js-beautify
  autocmd FileType java AutoFormatBuffer google-java-format
  autocmd FileType python AutoFormatBuffer yapf
  " Alternative: autocmd FileType python AutoFormatBuffer autopep8
augroup END
" 开场启动newcomplete
let g:neocomplete#enable_at_startup = 1
set t_Co=256
set bg=dark
color gruvbox
set shiftwidth=4
set tabstop=4
set nu
set cursorcolumn
set cursorline

" 按键映射
" NerdTree
map <C-n> :NERDTreeToggle<CR>
" incsearch
set hlsearch
" inc-search
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
